---
title: "Final Project: Fig. 3 Replication"
authors: "Anthony Hein, Briana Macedo, Manya Kapoor"
output: html_notebook
---

```{r} 
# Reading in files
library(readxl)
file3 <- read_excel("hCRISPRi_Library.xlsx",col_names = c("ID", "Gene", "TSS", "Protospacer", "Rank", "Predicted Activity Score", "Empirical Score", "Off-Target Stringency", "Predicted Score 2.1", "Sublibrary", "Sublib Half"), na = "nan", skip = 9)
file7 <- read_excel("hCRISPRi_GrowthPhenotype.xlsx", col_names = c("ID", "T0_R1", "E_R1", "T0_R2", "E_R2", "gamma_R1", "gamma_R2", "gamma_avg"), na = "nan", skip = 2)
file8 <- read_excel("hCRISPRi_pVals.xlsx", col_names = c("Gene", "R1_Transcripts", "R1_MWP", "R1_AvgP3", "R1_sgRNApass", "R2_Transcripts", "R2_MWP", "R2_AvgP3", "R2_sgRNApass", "Avg_Transcripts", "Avg_MWP", "Avg_AvgP3", "Avg_sgRNApass","Hart_class", "Evers_class", "BCRamp_Wang"), na = "nan", skip = 2)
```

```{r}
# Standardizing Order
file3 <- file3[order(file3$ID),]
file7 <- file7[order(file7$ID),]
```

```{r}
# Selecting Top5 most effective sgRNA for the smaller 5 sgRNA/gene library
file3_Top5 <- file3
file3_Top5 <- subset(file3, file3$`Sublib Half` == "Top5")
file7_Top5 <- subset(file7, file7$ID %in% file3_Top5$ID)
```

```{r}
# Extracting avg sgRNA counts and growth phenotypes for 10 and 5 sgRNA/gene
file7_counts <- as.data.frame(matrix(nrow = nrow(file7), ncol = 3))
file7_Top5_counts <- as.data.frame(matrix(nrow = nrow(file7_Top5), ncol = 3))

file7_counts[,1] <- file7[,1]
file7_counts[,2] <- rowMeans(cbind(file7[,3] - file7[,2], file7[,5] - file7[,4]))
file7_counts[,3] <- file7[,8]
file7_Top5_counts[,1] <- file7_Top5[,1]
file7_Top5_counts[,2] <- rowMeans(cbind(file7_Top5[,3] - file7_Top5[,2], file7_Top5[,5] - file7_Top5[,4]))
file7_Top5_counts[,3] <- file7_Top5[,8]
```

```{r}
# Extracting predicted activity scores for 10 and 5 sgRNA/gene
file3_score <- as.data.frame(matrix(nrow = nrow(file3), ncol = 2))
file3_Top5_score <- as.data.frame(matrix(nrow = nrow(file3_Top5), ncol = 2))

file3_score[,1] <- file3[,1]
file3_score[,2] <- file3[,9]
file3_Top5_score[,1] <- file3_Top5[,1]
file3_Top5_score[,2] <- file3_Top5[,9]
```


```{r}
# RE to extract predicted activity scores for essential genes (from p_value file 8)
Evers_essential_genes <- subset(file8, file8$Evers_class == "essential")$Gene
Evers_compare <- unique(grep(paste("^",Evers_essential_genes,"_",collapse="|",sep=""), file3_Top5_score$V1, value=TRUE))
Evers_Top5_activity <- file3_Top5_score[match(Evers_compare, file3_Top5_score[,1]),1:2]

# histogram sorting essential genes by predicted activity score
hist(Evers_Top5_activity[,2], breaks = seq(from = -0.2, to = 1.2, by=0.1))

# Easier way 
# Evers_essential_genes <- subset(file8, file8$Evers_class == "essential")$Gene
# Evers_Top5_activity <- subset(file3_Top5_score, file3_Top5_score$V1 %in% Evers_essential_genes)
# hist(Evers_Top5_activity[,2], breaks = seq(from = -0.2, to = 1.2, by=0.1))
```

```{r}
# RE to extract growth phenotypes for essential genes (from p_value file 8)
Evers_Top5_gamma_list <- unique(grep(paste("^",Evers_essential_genes,"_",collapse="|",sep=""), file7_Top5_counts$V1, value=TRUE))
Evers_Top5_gamma <- file7_Top5_counts[match(Evers_Top5_gamma_list, file7_Top5_counts[,1]),1:3]

# RE to extract growth phenotypes for non-essential genes (from p_value file 8)
Evers_nonessential_genes <- subset(file8, file8$Evers_class == "non-essential")$Gene
Evers_Top5_NE_gamma_list <- unique(grep(paste("^",Evers_nonessential_genes,"_",collapse="|",sep=""), file7_Top5_counts$V1, value=TRUE))
Evers_Top5_NE_gamma <- file7_Top5_counts[match(Evers_Top5_NE_gamma_list, file7_Top5_counts[,1]),1:3]

# Normalizing essential genes by non-essential gene distribution
Evers_NE_mean <- mean(Evers_Top5_NE_gamma[,3], na.rm = TRUE)
Evers_NE_SD <- sd(Evers_Top5_NE_gamma[,3], na.rm = TRUE)
std_Evers_Top5_gamma <- (Evers_Top5_gamma[,3] - Evers_NE_mean)/Evers_NE_SD

# Sorting growth phenotypes by predicted activity scores of those genes
Evers_cat <- cut(Evers_Top5_activity[,2], seq(-0.2,1.2,0.1))

# Boxplot to show growth phenotype for each category of predicted activity score
boxplot(std_Evers_Top5_gamma~Evers_cat)

```

```{r}
# Fig 3b

# For top5 library

Evers_Top5_gamma$V4 <- rep(c("E"), each=length(Evers_Top5_gamma$V1))
Evers_Top5_NE_gamma$V4 <- rep(c("NE"), each=length(Evers_Top5_NE_gamma$V1))
Evers_Top5_all <- rbind(Evers_Top5_gamma, Evers_Top5_NE_gamma)
Evers_Top5_all <- Evers_Top5_all[order(Evers_Top5_all$V3, na.last = NA),]
row.names(Evers_Top5_all) <- c(1:length(Evers_Top5_all$V1))
```

```{r}
E_count <- 1
NE_count <- 1
for(i in 1:length(Evers_Top5_all$V1)){
  if(Evers_Top5_all$V4[i] == "E"){
    Evers_Top5_all$V5[i] <- E_count/length(Evers_Top5_gamma$V4) 
    if (i == 1){
      Evers_Top5_all$V6[i] <- 0
    }
    else{
      Evers_Top5_all$V6[i] <- Evers_Top5_all$V6[i-1]
    }
    E_count <- E_count+1 
  }
  if(Evers_Top5_all$V4[i] == "NE"){
    Evers_Top5_all$V6[i] <- NE_count/length(Evers_Top5_NE_gamma$V4) 
    if (i == 1){
      Evers_Top5_all$V5[i] <- 0
    }
    else{
      Evers_Top5_all$V5[i] <- Evers_Top5_all$V5[i-1]
    }
    NE_count <- NE_count+1 
  }
}

```

```{r}
# All 10

Evers_gamma_list <- unique(grep(paste("^",Evers_essential_genes,"_",collapse="|",sep=""), file7_counts$V1, value=TRUE))
Evers_gamma <- file7_counts[match(Evers_gamma_list, file7_counts[,1]),1:3]

# RE to extract growth phenotypes for non-essential genes (from p_value file 8)
Evers_NE_gamma_list <- unique(grep(paste("^",Evers_nonessential_genes,"_",collapse="|",sep=""), file7_counts$V1, value=TRUE))
Evers_NE_gamma <- file7_counts[match(Evers_NE_gamma_list, file7_counts[,1]),1:3]
```

```{r}
Evers_gamma$V4 <- rep(c("E"), each=length(Evers_gamma$V1))
Evers_NE_gamma$V4 <- rep(c("NE"), each=length(Evers_NE_gamma$V1))
Evers_all <- rbind(Evers_gamma, Evers_NE_gamma)
Evers_all <- Evers_all[order(Evers_all$V3, na.last = NA),]
row.names(Evers_all) <- c(1:length(Evers_all$V1))
```

```{r}
E_count <- 1
NE_count <- 1
for(i in 1:length(Evers_all$V1)){
  if(Evers_all$V4[i] == "E"){
    Evers_all$V5[i] <- E_count/length(Evers_gamma$V4) 
    if (i == 1){
      Evers_all$V6[i] <- 0
    }
    else{
      Evers_all$V6[i] <- Evers_all$V6[i-1]
    }
    E_count <- E_count+1 
  }
  if(Evers_all$V4[i] == "NE"){
    Evers_all$V6[i] <- NE_count/length(Evers_NE_gamma$V4) 
    if (i == 1){
      Evers_all$V5[i] <- 0
    }
    else{
      Evers_all$V5[i] <- Evers_all$V5[i-1]
    }
    NE_count <- NE_count+1 
  }
}

plot(Evers_Top5_all$V6, Evers_Top5_all$V5, col = "dark blue")
points(Evers_all$V6, Evers_all$V5, col = "light blue")


```

```{r}
# Fig 3d

Hart_essential_genes <- subset(file8, file8$Hart_class == "essential")$Gene
Hart_nonessential_genes <- subset(file8, file8$Hart_class == "non-essential")$Gene

# 5 sgRNA/gene
gene_Top5_gamma <- c()
NE_gene_Top5_gamma <- c()

for (i in 1:length(Hart_essential_genes)){
  gene_Top5_gamma[i] <- mean(file7_Top5_counts[match(unique(grep(paste("^",Hart_essential_genes[i],"_",collapse="|",sep=""), file7_Top5_counts$V1, value=TRUE)), file7_Top5_counts[,1]),3], na.rm = TRUE)
}

Hart_Top5_gamma <- as.data.frame(cbind(Hart_essential_genes, gene_Top5_gamma))
colnames(Hart_Top5_gamma) <- c("V1", "V2")


for (i in 1:length(Hart_nonessential_genes)){
  NE_gene_Top5_gamma[i] <- mean(file7_Top5_counts[match(unique(grep(paste("^",Hart_nonessential_genes[i],"_",collapse="|",sep=""), file7_Top5_counts$V1, value=TRUE)), file7_Top5_counts[,1]),3], na.rm = TRUE)
}

Hart_Top5_NE_gamma <- as.data.frame(cbind(Hart_nonessential_genes, NE_gene_Top5_gamma))
colnames(Hart_Top5_NE_gamma) <- c("V1", "V2")

Hart_Top5_gamma$V3 <- rep(c("E"), each=length(Hart_Top5_gamma$V2))
Hart_Top5_NE_gamma$V3 <- rep(c("NE"), each=length(Hart_Top5_NE_gamma$V2))
Hart_Top5_all <- rbind(Hart_Top5_gamma, Hart_Top5_NE_gamma)
Hart_Top5_all$V2 <- abs(as.numeric(Hart_Top5_all$V2))
Hart_Top5_all <- Hart_Top5_all[order(-Hart_Top5_all$V2, na.last = NA),]
row.names(Hart_Top5_all) <- c(1:length(Hart_Top5_all$V1))

```

```{r}
E_count <- 1
NE_count <- 0
for(i in 1:length(Hart_Top5_all$V1)){
  if(Hart_Top5_all$V3[i] == "E"){
    Hart_Top5_all$V4[i] <- E_count/length(Hart_Top5_gamma$V3) 
    E_count <- E_count+1 
  }
  if(Hart_Top5_all$V3[i] == "NE"){
    if(i==1){
      Hart_Top5_all$V4[i] <- 0
    }
    else{
      Hart_Top5_all$V4[i] <-  Hart_Top5_all$V4[i-1]
    }
    NE_count <- NE_count+1 
  }
  Hart_Top5_all$V5[i] <- (E_count-1)/(E_count + NE_count - 1)
}


```

```{r}
# 10 sgRNA/gene

gene_gamma <- c()
NE_gene_gamma <- c()

for (i in 1:length(Hart_essential_genes)){
  gene_gamma[i] <- mean(file7_counts[match(unique(grep(paste("^",Hart_essential_genes[i],"_",collapse="|",sep=""), file7_counts$V1, value=TRUE)), file7_counts[,1]),3], na.rm = TRUE)
}

Hart_gamma <- as.data.frame(cbind(Hart_essential_genes, gene_gamma))
colnames(Hart_gamma) <- c("V1", "V2")


for (i in 1:length(Hart_nonessential_genes)){
  NE_gene_gamma[i] <- mean(file7_counts[match(unique(grep(paste("^",Hart_nonessential_genes[i],"_",collapse="|",sep=""), file7_counts$V1, value=TRUE)), file7_counts[,1]),3], na.rm = TRUE)
}

Hart_NE_gamma <- as.data.frame(cbind(Hart_nonessential_genes, NE_gene_gamma))
colnames(Hart_NE_gamma) <- c("V1", "V2")

Hart_gamma$V3 <- rep(c("E"), each=length(Hart_gamma$V2))
Hart_NE_gamma$V3 <- rep(c("NE"), each=length(Hart_NE_gamma$V2))
Hart_all <- rbind(Hart_gamma, Hart_NE_gamma)
Hart_all$V2 <- abs(as.numeric(Hart_all$V2))
Hart_all <- Hart_all[order(-Hart_all$V2, na.last = NA),]
row.names(Hart_all) <- c(1:length(Hart_all$V1))

```

```{r}
E_count <- 1
NE_count <- 0
for(i in 1:length(Hart_all$V1)){
  if(Hart_all$V3[i] == "E"){
    Hart_all$V4[i] <- E_count/length(Hart_gamma$V3) 
    E_count <- E_count+1 
  }
  if(Hart_all$V3[i] == "NE"){
    if(i==1){
      Hart_all$V4[i] <- 0
    }
    else{
      Hart_all$V4[i] <-  Hart_all$V4[i-1]
    }
    NE_count <- NE_count+1 
  }
  Hart_all$V5[i] <- (E_count-1)/(E_count + NE_count - 1)
}

par(pty ="s")
plot(Hart_Top5_all$V4,Hart_Top5_all$V5,col = "dark blue", type="l")
lines(Hart_all$V4,Hart_all$V5, col="light blue")
```

```{r}
#Fig 3c
```
